### ISSUE TITLE
[츄리닝안경 네오] 스트림 방식으로 데이터를 처리하는 kafka에서 file 시스템의 변경사항을 처리한다는게 이해가 잘 가지 않습니다.

### ISSUE THREAD

**Issue by bmh8993** [bmh8993/kafka-study#2]
선생님들 안녕하세요. 휴일에 실례인걸 알지만… 카프카 책 1장을 보다가 이해가 잘 가지 않는 점이 있어서 질문글 올립니다.

1장 33p에 보면 event bus와 kafka의 성능 차이의 이유로 OS의 fsync API 처리방식을 언급하고 있는데요. fsync는 하드 디스크에 file의 변경사항을 기록하는 API call이라고 알고 있습니다.

디스크에 기록이야 당연히 되는거겠지만, 스트림 방식으로 데이터를 처리하는 kafka에서 file 시스템의 변경사항을 처리한다는게 이해가 잘 가지 않습니다. Kafka 뿐만 아니라 OS에 대한 내용이 섞여있다보니 그런것 같기도 합니다.

혹시 이 부분에 참고할만한 개념이나 설명 가능하신 선생님들 계실까요? 감사합니다!!

**Comment by bmh8993** [comment]
https://blog.twitter.com/engineering/en_us/topics/insights/2018/twitters-kafka-adoption-story

관련된 트위터의 블로그 글을 직접 읽어봤습니다.
제가 네오님의 질문을 이해하기로는 스트림 방식인데 file 시스템의 변경사항을 처리하는데 어떻게 성능이 나올까? 라는 질문으로 이해했습니다.
해당 글에서는 event bus의 경우 wirte/read proxy를 두어서 여러 계층을 거쳐서 처리가 이루어지는데 kafka는 단일 호스트로 동일한 과정이 처리되기 때문에 리소스 절약이 된다 라고이야기 합니다. 그러니까 결국 fsync와 같은 디스크에 쓰기는 동일하게 발생하지만 처리방식에서 오는 리소스 효율이다 이것이 결론으로 보입니다.

질문을 잘못 이해했다면ㅎㅎ 어쩔 수 없지만 그래도 재미있는 글을 읽게 되었네요

**Comment by lagunerio** [comment]
질문 주신 덕분에 저도 앞 장 내용을 좀 더 자세히 읽어볼 수 있었습니다. 흥미로운 주제여서 저도 찾아본 내용 공유해봅니다!

덧붙여서 지금 4장을 공부하고 있는데요, bmh8993님께서 말씀하신 '제로카피'와 더불어서 'ACK 통신을 없애는 방법으로 통신 리소스를 높였다(p124)'는 내용을 공부해보니 이벤트 버스와 카프카의 처리량에 따른 latency를 비교한 결과가 좀 더 명확하게 이해가 되는 것 같습니다.

추가로 SSD와 관련된 내용이 있어서 찾아보니 이런 자료도 있네요([참고](https://team-platform.tistory.com/6)).

**Comment by bmh8993** [comment]
@lagunerio 오우 4장을 읽어볼 때 말씀해주신 내용을 다시 보면서 읽어봐야겠네요 감사합니다!
